server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.119.139.32:8848
  datasource:
    url: jdbc:mysql://localhost:3306/coin-exchange?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: redis-server
#    port: 6380
#    password: Ltd3411??